apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deploy
  namespace: ingress-nginx
spec:
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back-cnt
          image: terezabisharyan/app-server:c1872d11d61243e72f0957019a2be40f323ca735
          ports:
            - containerPort: 5000
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: pg-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: PASSWORD
