apiVersion: v1
kind: Service
metadata:
  name: pg-service
  namespace: ingress-nginx
  labels:
    db: postgres
spec:
  clusterIP: None
  selector:
    db: postgres
  ports:
    - port: 5432
      targetPort: 5432
