apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume-1
spec:
  #storageClassName: standard
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.0.111
    path: "/srv/nfs/shared_dir_1"
  #claimRef:
    #name: db-pvc
    #namespace: ingress-nginx
