apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume-1
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.0.111
    path: "/srv/nfs/shared_dir_1"
