apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-sts
spec:
  serviceName: "pg-service"
  replicas: 1
  selector:
    matchLabels:
      db: postgres
  template:
    metadata:
      labels:
        db: postgres
    spec:
      containers:
      - name: pg-cnt
        image: postgres
        volumeMounts:
        - name: db-volume
          mountPath: /var/lib/postgresql/data
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-password
                key: PASSWORD 
  volumeClaimTemplates:
  - metadata:
      name: db-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Mi
